version: "3.1"
services:
  envoy-one:
    image: envoy:one
    command: /usr/local/bin/envoy --log-level trace --component-log-level upstream:info -c /etc/envoy/envoy.yaml
    networks:
      - envoytest
    ports:
      - "9901:9901"
      - "10001:10001"
  envoy-two:
    image: envoy:two
    command: /usr/local/bin/envoy --log-level trace --component-log-level upstream:info -c /etc/envoy/envoy.yaml
    networks:
      - envoytest
    ports:
      - "9902:9902"
      - "10002:10002"
networks:
  envoytest:
